import React from "react";
import { BottomTab, TopTab, AnggotaList, Footer } from "../components";

const Nasabah = () => {
  const dummyNasabah = [
    {
      id: 1,
      sobekan: "25",
      nama: "Nael Saruksuk",
      jenis: "h",
      alamat: "Puri Nirwana",
      status: "Lancar",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
    },
    {
      id: 2,
      sobekan: "2",
      nama: "Fallah Ayuningrum",
      jenis: "h",
      alamat: "Bumi Kahuripan Indah",
      status: "Lancar",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
    },
    {
      id: 3,
      sobekan: "4",
      nama: "Anim",
      jenis: "h",
      alamat: "Pelaukan",
      status: "Lancar",
      angsuran: "35 ribu",
      tanggal: "9 Jun",
    },
    {
      id: 4,
      sobekan: "17",
      nama: "Enih",
      jenis: "h",
      alamat: "Pelaukan",
      status: "Lancar",
      angsuran: "20 ribu",
      tanggal: "9 Jun",
    },
    {
      id: 5,
      sobekan: "11",
      nama: "Erna",
      jenis: "h",
      alamat: "Pelaukan",
      status: "Lancar",
      angsuran: "15 ribu",
      tanggal: "9 Jun",
    },
    {
      id: 6,
      sobekan: "15",
      nama: "Nenek",
      jenis: "h",
      alamat: "Pule",
      status: "Lancar",
      angsuran: "40 ribu",
      tanggal: "8 Jun",
    },
    {
      id: 7,
      sobekan: "8",
      nama: "Ani",
      jenis: "h",
      alamat: "Pule",
      status: "Lancar",
      angsuran: "15 ribu",
      tanggal: "8 Jun",
    },
    {
      id: 8,
      sobekan: "22",
      nama: "Nia",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Lancar",
      angsuran: "25 ribu",
      tanggal: "7 Jun",
    },
    {
      id: 9,
      sobekan: "14",
      nama: "Opung",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Lancar",
      angsuran: "25 ribu",
      tanggal: "7 Jun",
    },
    {
      id: 10,
      sobekan: "5",
      nama: "Dalisah",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Lancar",
      angsuran: "10 ribu",
      tanggal: "6 Jun",
    },
    {
      id: 12,
      sobekan: "6",
      nama: "Apupah",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Lancar",
      angsuran: "30 ribu",
      tanggal: "6 Jun",
    },
    {
      id: 13,
      sobekan: "9",
      nama: "Umdah",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Lancar",
      angsuran: "50 ribu",
      tanggal: "6 Jun",
    },
    {
      id: 14,
      sobekan: "12",
      nama: "Asiah",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Lancar",
      angsuran: "75 ribu",
      tanggal: "6 Jun",
    },
    {
      id: 15,
      sobekan: "16",
      nama: "Marni",
      jenis: "h",
      alamat: "Pulo Bambu",
      status: "Sedang",
      angsuran: "250 ribu",
      tanggal: "5 Jun",
    },
    {
      id: 16,
      sobekan: "7",
      nama: "Lulu",
      jenis: "h",
      alamat: "Pilar Barat",
      status: "Lancar",
      angsuran: "20 ribu",
      tanggal: "5 Jun",
    },
    {
      id: 17,
      sobekan: "10",
      nama: "Atih",
      jenis: "h",
      alamat: "Pilar Barat",
      status: "Lancar",
      angsuran: "15 ribu",
      tanggal: "5 Jun",
    },
    {
      id: 18,
      sobekan: "13",
      nama: "Sri",
      jenis: "h",
      alamat: "Pilar Barat",
      status: "Lancar",
      angsuran: "10 ribu",
      tanggal: "5 Jun",
    },
    {
      id: 19,
      sobekan: "20",
      nama: "Yuli",
      jenis: "h",
      alamat: "Teleng",
      status: "Lancar",
      angsuran: "40 ribu",
      tanggal: "4 Jun",
    },
    {
      id: 20,
      sobekan: "18",
      nama: "Susanti",
      jenis: "h",
      alamat: "Teleng",
      status: "Lancar",
      angsuran: "10 ribu",
      tanggal: "4 Jun",
    },
  ];

  return (
    <>
      <TopTab />
      <AnggotaList anggotas={dummyNasabah} />
      <Footer />
      <BottomTab />
    </>
  );
};

export default Nasabah;
