import React from "react";
import { BottomTab, TopTab, AnggotaList, Footer } from "../components";
import "../assets/fotoNasabah/nael.png";

const Nasabah = () => {
  const dummyNasabah = [
    {
      id: 1,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 2,
      foto: "src/assets/fotoNasabah/ivan.jpg",
      nama: "Ivan Pasaribu",
      angsuran: "100 ribu",
      tanggal: "8 Jun",
      alamat: "Puri Nirwana",
      sobekan: "5",
    },
    {
      id: 3,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 4,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 5,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 6,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 7,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 8,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 9,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 10,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 11,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 12,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 13,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 14,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 15,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 16,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 17,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 18,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 19,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 20,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Nael Saruksuk",
      angsuran: "150 ribu",
      tanggal: "9 Jun",
      alamat: "Puri Nirwana",
      sobekan: "1",
    },
    {
      id: 21,
      foto: "src/assets/fotoNasabah/nael.png",
      nama: "Ivan Saruksuk",
      angsuran: "500 ribu",
      tanggal: "8 Jun",
      alamat: "Puri Nirwana",
      sobekan: "2",
    },
  ];

  return (
    <>
      <TopTab />
      <AnggotaList anggotas={dummyNasabah} />
      <Footer />
      <BottomTab />
    </>
  );
};

export default Nasabah;
